# Generated by Django 4.2.2 on 2025-02-06 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('datestr', models.CharField(max_length=13)),
                ('end', models.BooleanField(default=False)),
                ('opponent', models.CharField(max_length=10)),
                ('players', models.CharField(max_length=999)),
                ('serves', models.CharField(max_length=999)),
                ('results', models.CharField(max_length=999)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('grade', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
